"""Add UniqueConstraint to latlon_suitability

Revision ID: 7bc3b56f8026
Revises: a3d62aaed7cc
Create Date: 2026-05-06 16:46:53.942899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc3b56f8026'
down_revision: Union[str, Sequence[str], None] = 'a3d62aaed7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('latlon_suitability', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('latlon_suitability', 'soil_sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('latlon_suitability', 'stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint('_farm_sample_stage_uc', 'latlon_suitability', ['farm_id', 'soil_sample_id', 'stage'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_farm_sample_stage_uc', 'latlon_suitability', type_='unique')
    op.alter_column('latlon_suitability', 'stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('latlon_suitability', 'soil_sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('latlon_suitability', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
