"""Initial clean normalized schema v2

Revision ID: a3d62aaed7cc
Revises: 
Create Date: 2026-05-06 16:24:29.841769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a3d62aaed7cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_master',
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('crop_id')
    )
    op.create_index(op.f('ix_crop_master_crop_id'), 'crop_master', ['crop_id'], unique=False)
    op.create_table('farmer',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('aadhaar_encrypted', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_index(op.f('ix_farmer_farmer_id'), 'farmer', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_mobile'), 'farmer', ['mobile'], unique=True)
    op.create_table('score_model',
    sa.Column('score_model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('score_model_id')
    )
    op.create_index(op.f('ix_score_model_score_model_id'), 'score_model', ['score_model_id'], unique=False)
    op.create_table('soil_parameter_master',
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('ideal_min', sa.Float(), nullable=True),
    sa.Column('ideal_max', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('parameter_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_soil_parameter_master_parameter_id'), 'soil_parameter_master', ['parameter_id'], unique=False)
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_state_state_id'), 'state', ['state_id'], unique=False)
    op.create_table('district',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_district_district_id'), 'district', ['district_id'], unique=False)
    op.create_table('district_soil_summary',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.district_id'], ),
    sa.PrimaryKeyConstraint('district_id', 'year')
    )
    op.create_table('village',
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.district_id'], ),
    sa.PrimaryKeyConstraint('village_id')
    )
    op.create_index(op.f('ix_village_village_id'), 'village', ['village_id'], unique=False)
    op.create_table('farm',
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('farm_name', sa.String(length=150), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.village_id'], ),
    sa.PrimaryKeyConstraint('farm_id')
    )
    op.create_index(op.f('ix_farm_farm_id'), 'farm', ['farm_id'], unique=False)
    op.create_table('crop_recommendation',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.crop_id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_crop_recommendation_recommendation_id'), 'crop_recommendation', ['recommendation_id'], unique=False)
    op.create_table('farm_crop',
    sa.Column('farm_crop_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.crop_id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('farm_crop_id')
    )
    op.create_index(op.f('ix_farm_crop_farm_crop_id'), 'farm_crop', ['farm_crop_id'], unique=False)
    op.create_table('soil_health_score',
    sa.Column('soil_health_score_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('score_model_id', sa.Integer(), nullable=True),
    sa.Column('score_value', sa.Float(), nullable=True),
    sa.Column('score_category', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.ForeignKeyConstraint(['score_model_id'], ['score_model.score_model_id'], ),
    sa.PrimaryKeyConstraint('soil_health_score_id')
    )
    op.create_index(op.f('ix_soil_health_score_soil_health_score_id'), 'soil_health_score', ['soil_health_score_id'], unique=False)
    op.create_table('soil_sample',
    sa.Column('soil_sample_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('sample_date', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('soil_sample_id')
    )
    op.create_index(op.f('ix_soil_sample_soil_sample_id'), 'soil_sample', ['soil_sample_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_index(op.f('ix_weather_data_weather_id'), 'weather_data', ['weather_id'], unique=False)
    op.create_table('latlon_suitability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('soil_sample_id', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=True),
    sa.Column('village_name', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('organic_carbon', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('shs_score', sa.Float(), nullable=True),
    sa.Column('shs_category', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.ForeignKeyConstraint(['soil_sample_id'], ['soil_sample.soil_sample_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latlon_suitability_id'), 'latlon_suitability', ['id'], unique=False)
    op.create_table('soil_parameter_value',
    sa.Column('param_value_id', sa.Integer(), nullable=False),
    sa.Column('soil_sample_id', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['soil_parameter_master.parameter_id'], ),
    sa.ForeignKeyConstraint(['soil_sample_id'], ['soil_sample.soil_sample_id'], ),
    sa.PrimaryKeyConstraint('param_value_id')
    )
    op.create_index(op.f('ix_soil_parameter_value_param_value_id'), 'soil_parameter_value', ['param_value_id'], unique=False)
    op.create_table('soil_score_component',
    sa.Column('soil_score_component_id', sa.Integer(), nullable=False),
    sa.Column('soil_health_score_id', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['soil_parameter_master.parameter_id'], ),
    sa.ForeignKeyConstraint(['soil_health_score_id'], ['soil_health_score.soil_health_score_id'], ),
    sa.PrimaryKeyConstraint('soil_score_component_id')
    )
    op.create_index(op.f('ix_soil_score_component_soil_score_component_id'), 'soil_score_component', ['soil_score_component_id'], unique=False)
    op.create_index(op.f('ix_country_country_id'), 'country', ['country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_country_id'), table_name='country')
    op.drop_index(op.f('ix_soil_score_component_soil_score_component_id'), table_name='soil_score_component')
    op.drop_table('soil_score_component')
    op.drop_index(op.f('ix_soil_parameter_value_param_value_id'), table_name='soil_parameter_value')
    op.drop_table('soil_parameter_value')
    op.drop_index(op.f('ix_latlon_suitability_id'), table_name='latlon_suitability')
    op.drop_index('idx_latlon_suitability_geom', table_name='latlon_suitability', postgresql_using='gist')
    op.drop_table('latlon_suitability')
    op.drop_index(op.f('ix_weather_data_weather_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_soil_sample_soil_sample_id'), table_name='soil_sample')
    op.drop_index('idx_soil_sample_geom', table_name='soil_sample', postgresql_using='gist')
    op.drop_table('soil_sample')
    op.drop_index(op.f('ix_soil_health_score_soil_health_score_id'), table_name='soil_health_score')
    op.drop_table('soil_health_score')
    op.drop_index(op.f('ix_farm_crop_farm_crop_id'), table_name='farm_crop')
    op.drop_table('farm_crop')
    op.drop_index(op.f('ix_crop_recommendation_recommendation_id'), table_name='crop_recommendation')
    op.drop_table('crop_recommendation')
    op.drop_index(op.f('ix_farm_farm_id'), table_name='farm')
    op.drop_index('idx_farm_geom', table_name='farm', postgresql_using='gist')
    op.drop_table('farm')
    op.drop_index(op.f('ix_village_village_id'), table_name='village')
    op.drop_table('village')
    op.drop_index('idx_district_soil_summary_geom', table_name='district_soil_summary', postgresql_using='gist')
    op.drop_table('district_soil_summary')
    op.drop_index(op.f('ix_district_district_id'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_state_state_id'), table_name='state')
    op.drop_table('state')
    op.drop_index(op.f('ix_soil_parameter_master_parameter_id'), table_name='soil_parameter_master')
    op.drop_table('soil_parameter_master')
    op.drop_index(op.f('ix_score_model_score_model_id'), table_name='score_model')
    op.drop_table('score_model')
    op.drop_index(op.f('ix_farmer_mobile'), table_name='farmer')
    op.drop_index(op.f('ix_farmer_farmer_id'), table_name='farmer')
    op.drop_table('farmer')
    op.drop_index(op.f('ix_crop_master_crop_id'), table_name='crop_master')
    op.drop_table('crop_master')
    # ### end Alembic commands ###
